TOKEN = "YOUR_TOKEN"
way = 'YOUR_FILE_WHERE_HOMEWORK_WILL_BE_STORED.dat'
students = ['SURNAME NAME', 'SURNAME NAME', 'SURNAME NAME' ...]
color = 0x######
bot_activity = 'STATUS'
edit_role = 'ROLE_WHICH_CAN_CREATE_AND_EDIT_HOMEWORKS'
